# Generated by Django 5.1.6 on 2025-02-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='Certi_image',
            field=models.CharField(default='image', max_length=255),
        ),
    ]
