# Generated by Django 5.1.6 on 2025-02-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_certification_certi_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git_repo',
            field=models.CharField(default='github_repo', max_length=100),
        ),
    ]
