# Generated by Django 5.1.6 on 2025-02-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_project_git_repo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.CharField(default='project image', max_length=255),
        ),
    ]
