# Generated by Django 5.1.6 on 2025-02-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_project_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('message', models.CharField(max_length=255)),
                ('send_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
