# Generated by Django 5.1.6 on 2025-02-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_messagecontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecontact',
            name='username',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
