# Generated by Django 5.1.6 on 2025-02-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_messagecontact_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagecontact',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='messagecontact',
            old_name='message',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='messagecontact',
            old_name='username',
            new_name='Username',
        ),
        migrations.RemoveField(
            model_name='messagecontact',
            name='send_date',
        ),
    ]
